# Generated by Django 2.2.4 on 2019-10-17 01:44

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'area_data.json'
def load_data(apps, schema_editor):
    Area = apps.get_model('store', 'Area')
    jsonFile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonFile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT ({longitude} {latitude})', srid=4326)
                    Store(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_area'),
    ]

    operations = [
    ]
