# Generated by Django 2.2.4 on 2019-08-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quanity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
