# Generated by Django 2.2.4 on 2019-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190806_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quanity',
            field=models.IntegerField(default=1),
        ),
    ]
