# Generated by Django 2.2.4 on 2019-09-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190911_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'Sale'), ('B', 'Back to School'), ('P', 'Promotion')], max_length=2, null=True),
        ),
    ]
